<?php
/**
 * @file Contains logic for file_browser.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function file_browser_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the file_browser module.
    case 'help.page.file_browser':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides an entity browser for files.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function file_browser_form_alter(&$form, FormStateInterface &$form_state) {
  // Normal form overrides.
  if (isset($form['#form_id']) && $form['#form_id'] == 'entity_browser_browse_files_form') {
    // Attach our library.
    $form['#attached']['library'][] = 'file_browser/view';

    // Style the submit button.
    $form['actions']['submit']['#value'] = t('Select Files');
    $form['actions']['submit']['#attributes']['class'][] = 'button--primary';

    // Wrap actions so we can float them at the bottom of the browser.
    $form['actions_wrap'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => 'file-browser-actions',
      ],
      0 => $form['actions'],
    ];
    unset($form['actions']);
  }
}

/**
 * Implements hook_preprocess_details().
 */
function file_browser_preprocess_details(&$variables) {
  if ($variables['element']['#id'] == 'edit-field-file-browser-reference') {
    $variables['#attached']['library'][] = 'file_browser/iframe';
  }
}
